export const GET_CALL_DATA = "GET_CALL_DATA";
export const GET_CALL_DATA_FAILED = "GET_CALL_DATA_FAILED";
export const UPDATE_CALL_DATA_FETCHING = "UPDATE_CALL_DATA_FETCHING";
export const UPDATE_CALL_DATA = "UPDATE_CALL_DATA";
export const UPDATE_CALL_DATA_FAILED = "UPDATE_CALL_DATA_FAILED";
export const UPDATE_CALL_DATA_RESET = "UPDATE_CALL_DATA_RESET";
